#!/bin/bash
#### Adds line to source custom alias generation file
__learnings-init-func () {
	local SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
	local LEARNINGS_SRC=learnings-source
	local LINE='[ -f '"${SCRIPTPATH}"'/'"${LEARNINGS_SRC}"' ] && . '"${SCRIPTPATH}"/"${LEARNINGS_SRC}"
	local FILE=~/.bash_aliases
	#### add line to FILE if needed to source LEARNINGS_SRC
	if [ ! -f "${FILE}" ]; then
		echo "${FILE}" does not exist, creating... ; touch "${FILE}"
	fi
	grep -qF -- "${LINE}" "${FILE}" || (echo -e "\n${LINE}" >> "${FILE}" && echo "${LEARNINGS_SRC}" added to "${FILE}") || return 1
}
####
__learnings-init-func
exit "${?}"